from dash import html
from .itemhistory import itemHistory
from utils import (
    convert_duration_to_min_sec,
    convert_timestamp_to_occurence_str,
    convert_queueid_to_gamemode,
)

test = {
    "metadata": {
        "dataVersion": "2",
        "matchId": "EUW1_7317717857",
        "participants": [
            "g1copFYH9dR7BeDAVOcjNu7iiTYj6BR7qd6PnbNQ4holfd0wuRYqLk39PSWRWewQisOvcAc2h3vpzw",
            "FUmDyGbTulXXe4DHZ3vZnTTRGLRNKkPxsUKw8ElGv8qoO36vAzkP2aBL43qaVejqk_F6hTmq4uuPOQ",
            "Ku7BSayr629wpDZGe66XPPjJHxACvXHgVRiynHQ0O1um9q1jfNVRf_u4I81uZjC60mVVKjiyoZ5-2A",
            "EKEtQL7IYeF_4invvlJBjHhVFu5eDnU7k5kxhSKRNw_M_-cF2I-IFnm1eF6HV6V0-RgYyl_aJDu2DQ",
            "b6m6GEbyxnQsS5AjXpn_koak2PAPAvdz4VzUqZ1to1GZsIh4X7Hk_H4q-DYBEgowEYPAAKmUhF_jmw",
            "qAy31qSL-jpql4a1dNC9F_ptfccA5OWiWenBoOocVRmEMDNr8TfHLlmEcYu53X_uPR1pxwUXHzLe9w",
            "DL56H2gRcMXeQTj5ODI6Xcm9gaj1Jfi59b9CVs5gn3caKlacsLxJhZNB6J79X9stSGudVy0Hvy28tA",
            "19axn_a4f3-crc50ifaB0mihXEZJLvm9ZHgtQm6uIKICZiR6Jl1803TrqfhuPVO9Fltegyq7rmgNzA",
            "uzXr4u-YJuL0odNwlJaJo0yuwkPv6KGFZstAwbbI3v3aWY9ytsnPy_S_Wi8mC73SvwDu4ooD0SPxMA",
            "saAigrIZNm4OXUPBoBbu6EAewEW3kgAcA5HYW0gX_uV1ivEh8Cqx25mbHX85aFDFX4wYiYlCw-dGSA",
        ],
    },
    "info": {
        "endOfGameResult": "GameComplete",
        "gameCreation": 1740412834850,
        "gameDuration": 2836,
        "gameEndTimestamp": 1740415753248,
        "gameId": 7317717857,
        "gameMode": "CLASSIC",
        "gameName": "teambuilder-match-7317717857",
        "gameStartTimestamp": 1740412917349,
        "gameType": "MATCHED_GAME",
        "gameVersion": "15.4.657.5386",
        "mapId": 11,
        "participants": [
            {
                "PlayerScore0": 0,
                "PlayerScore1": 0,
                "PlayerScore10": 0,
                "PlayerScore11": 0,
                "PlayerScore2": 0,
                "PlayerScore3": 0,
                "PlayerScore4": 0,
                "PlayerScore5": 0,
                "PlayerScore6": 0,
                "PlayerScore7": 0,
                "PlayerScore8": 0,
                "PlayerScore9": 0,
                "allInPings": 0,
                "assistMePings": 7,
                "assists": 5,
                "baronKills": 0,
                "basicPings": 0,
                "bountyLevel": 10,
                "challenges": {
                    "12AssistStreakCount": 0,
                    "HealFromMapSources": 0,
                    "InfernalScalePickup": 0,
                    "SWARM_DefeatAatrox": 0,
                    "SWARM_DefeatBriar": 0,
                    "SWARM_DefeatMiniBosses": 0,
                    "SWARM_EvolveWeapon": 0,
                    "SWARM_Have3Passives": 0,
                    "SWARM_KillEnemy": 0,
                    "SWARM_PickupGold": 0,
                    "SWARM_ReachLevel50": 0,
                    "SWARM_Survive15Min": 0,
                    "SWARM_WinWith5EvolvedWeapons": 0,
                    "abilityUses": 320,
                    "acesBefore15Minutes": 0,
                    "alliedJungleMonsterKills": 0,
                    "baronTakedowns": 1,
                    "blastConeOppositeOpponentCount": 0,
                    "bountyGold": 0,
                    "buffsStolen": 1,
                    "completeSupportQuestInTime": 0,
                    "controlWardsPlaced": 1,
                    "damagePerMinute": 749.1109182811055,
                    "damageTakenOnTeamPercentage": 0.21748375722996863,
                    "dancedWithRiftHerald": 0,
                    "deathsByEnemyChamps": 11,
                    "dodgeSkillShotsSmallWindow": 0,
                    "doubleAces": 0,
                    "dragonTakedowns": 1,
                    "earliestBaron": 1553.173913041,
                    "earliestDragonTakedown": 1915.562060078,
                    "earliestElderDragon": 1915.562060078,
                    "earlyLaningPhaseGoldExpAdvantage": 0,
                    "effectiveHealAndShielding": 0,
                    "elderDragonKillsWithOpposingSoul": 0,
                    "elderDragonMultikills": 1,
                    "enemyChampionImmobilizations": 25,
                    "enemyJungleMonsterKills": 0,
                    "epicMonsterKillsNearEnemyJungler": 0,
                    "epicMonsterKillsWithin30SecondsOfSpawn": 0,
                    "epicMonsterSteals": 0,
                    "epicMonsterStolenWithoutSmite": 0,
                    "firstTurretKilled": 1,
                    "firstTurretKilledTime": 932.693577932,
                    "fistBumpParticipation": 0,
                    "flawlessAces": 0,
                    "fullTeamTakedown": 1,
                    "gameLength": 2836.240949972,
                    "getTakedownsInAllLanesEarlyJungleAsLaner": 0,
                    "goldPerMinute": 433.8351904920657,
                    "hadOpenNexus": 0,
                    "immobilizeAndKillWithAlly": 8,
                    "initialBuffCount": 0,
                    "initialCrabCount": 0,
                    "jungleCsBefore10Minutes": 0,
                    "junglerTakedownsNearDamagedEpicMonster": 0,
                    "kTurretsDestroyedBeforePlatesFall": 0,
                    "kda": 1.3636363636363635,
                    "killAfterHiddenWithAlly": 0,
                    "killParticipation": 0.3333333333333333,
                    "killedChampTookFullTeamDamageSurvived": 2,
                    "killingSprees": 2,
                    "killsNearEnemyTurret": 3,
                    "killsOnOtherLanesEarlyJungleAsLaner": 0,
                    "killsOnRecentlyHealedByAramPack": 0,
                    "killsUnderOwnTurret": 0,
                    "killsWithHelpFromEpicMonster": 0,
                    "knockEnemyIntoTeamAndKill": 11,
                    "landSkillShotsEarlyGame": 0,
                    "laneMinionsFirst10Minutes": 76,
                    "laningPhaseGoldExpAdvantage": 0,
                    "legendaryCount": 0,
                    "legendaryItemUsed": [3078, 3742, 3053, 6665, 3033],
                    "lostAnInhibitor": 0,
                    "maxCsAdvantageOnLaneOpponent": 53,
                    "maxKillDeficit": 0,
                    "maxLevelLeadLaneOpponent": 1,
                    "mejaisFullStackInTime": 0,
                    "moreEnemyJungleThanOpponent": 0,
                    "multiKillOneSpell": 0,
                    "multiTurretRiftHeraldCount": 0,
                    "multikills": 2,
                    "multikillsAfterAggressiveFlash": 0,
                    "outerTurretExecutesBefore10Minutes": 0,
                    "outnumberedKills": 2,
                    "outnumberedNexusKill": 0,
                    "perfectDragonSoulsTaken": 1,
                    "perfectGame": 0,
                    "pickKillWithAlly": 11,
                    "playedChampSelectPosition": 1,
                    "poroExplosions": 0,
                    "quickCleanse": 0,
                    "quickFirstTurret": 0,
                    "quickSoloKills": 0,
                    "riftHeraldTakedowns": 0,
                    "saveAllyFromDeath": 0,
                    "scuttleCrabKills": 1,
                    "shortestTimeToAceFromFirstTakedown": 16.044243564,
                    "skillshotsDodged": 7,
                    "skillshotsHit": 0,
                    "snowballsHit": 0,
                    "soloBaronKills": 0,
                    "soloKills": 3,
                    "soloTurretsLategame": 1,
                    "stealthWardsPlaced": 15,
                    "survivedSingleDigitHpCount": 0,
                    "survivedThreeImmobilizesInFight": 0,
                    "takedownOnFirstTurret": 0,
                    "takedowns": 15,
                    "takedownsAfterGainingLevelAdvantage": 0,
                    "takedownsBeforeJungleMinionSpawn": 0,
                    "takedownsFirstXMinutes": 1,
                    "takedownsInAlcove": 0,
                    "takedownsInEnemyFountain": 0,
                    "teamBaronKills": 3,
                    "teamDamagePercentage": 0.16303730771540278,
                    "teamElderDragonKills": 2,
                    "teamRiftHeraldKills": 0,
                    "tookLargeDamageSurvived": 0,
                    "turretPlatesTaken": 2,
                    "turretTakedowns": 7,
                    "turretsTakenWithRiftHerald": 0,
                    "twentyMinionsIn3SecondsCount": 0,
                    "twoWardsOneSweeperCount": 0,
                    "unseenRecalls": 0,
                    "visionScoreAdvantageLaneOpponent": 0.2428523302078247,
                    "visionScorePerMinute": 0.6840132796256876,
                    "voidMonsterKill": 1,
                    "wardTakedowns": 2,
                    "wardTakedownsBefore20M": 0,
                    "wardsGuarded": 0,
                },
                "champExperience": 25394,
                "champLevel": 18,
                "championId": 122,
                "championName": "Darius",
                "championTransform": 0,
                "commandPings": 7,
                "consumablesPurchased": 4,
                "damageDealtToBuildings": 11990,
                "damageDealtToObjectives": 19389,
                "damageDealtToTurrets": 11990,
                "damageSelfMitigated": 99476,
                "dangerPings": 0,
                "deaths": 11,
                "detectorWardsPlaced": 1,
                "doubleKills": 2,
                "dragonKills": 1,
                "eligibleForProgression": True,
                "enemyMissingPings": 18,
                "enemyVisionPings": 6,
                "firstBloodAssist": False,
                "firstBloodKill": False,
                "firstTowerAssist": False,
                "firstTowerKill": False,
                "gameEndedInEarlySurrender": False,
                "gameEndedInSurrender": False,
                "getBackPings": 2,
                "goldEarned": 20507,
                "goldSpent": 18508,
                "holdPings": 0,
                "individualPosition": "TOP",
                "inhibitorKills": 4,
                "inhibitorTakedowns": 5,
                "inhibitorsLost": 1,
                "item0": 3742,
                "item1": 3009,
                "item2": 3078,
                "item3": 3053,
                "item4": 6665,
                "item5": 3033,
                "item6": 3340,
                "itemsPurchased": 26,
                "killingSprees": 3,
                "kills": 10,
                "lane": "MIDDLE",
                "largestCriticalStrike": 1001,
                "largestKillingSpree": 4,
                "largestMultiKill": 2,
                "longestTimeSpentLiving": 537,
                "magicDamageDealt": 0,
                "magicDamageDealtToChampions": 0,
                "magicDamageTaken": 23186,
                "missions": {
                    "playerScore0": 0,
                    "playerScore1": 0,
                    "playerScore2": 0,
                    "playerScore3": 0,
                    "playerScore4": 0,
                    "playerScore5": 0,
                    "playerScore6": 0,
                    "playerScore7": 0,
                    "playerScore8": 0,
                    "playerScore9": 0,
                    "playerScore10": 0,
                    "playerScore11": 0,
                },
                "needVisionPings": 1,
                "neutralMinionsKilled": 24,
                "nexusKills": 0,
                "nexusLost": 1,
                "nexusTakedowns": 0,
                "objectivesStolen": 0,
                "objectivesStolenAssists": 0,
                "onMyWayPings": 15,
                "participantId": 1,
                "pentaKills": 0,
                "perks": {
                    "statPerks": {"defense": 5001, "flex": 5008, "offense": 5005},
                    "styles": [
                        {
                            "description": "primaryStyle",
                            "selections": [
                                {"perk": 8010, "var1": 721, "var2": 0, "var3": 0},
                                {"perk": 9111, "var1": 1874, "var2": 300, "var3": 0},
                                {"perk": 9104, "var1": 20, "var2": 10, "var3": 0},
                                {"perk": 8299, "var1": 1441, "var2": 0, "var3": 0},
                            ],
                            "style": 8000,
                        },
                        {
                            "description": "subStyle",
                            "selections": [
                                {"perk": 8224, "var1": 44, "var2": 1433, "var3": 0},
                                {"perk": 8234, "var1": 18316, "var2": 0, "var3": 0},
                            ],
                            "style": 8200,
                        },
                    ],
                },
                "physicalDamageDealt": 266886,
                "physicalDamageDealtToChampions": 24361,
                "physicalDamageTaken": 29873,
                "placement": 0,
                "playerAugment1": 0,
                "playerAugment2": 0,
                "playerAugment3": 0,
                "playerAugment4": 0,
                "playerAugment5": 0,
                "playerAugment6": 0,
                "playerSubteamId": 0,
                "profileIcon": 5058,
                "pushPings": 0,
                "puuid": "g1copFYH9dR7BeDAVOcjNu7iiTYj6BR7qd6PnbNQ4holfd0wuRYqLk39PSWRWewQisOvcAc2h3vpzw",
                "quadraKills": 0,
                "retreatPings": 0,
                "riotIdGameName": "drυg in my drink",
                "riotIdTagline": "313",
                "role": "DUO",
                "sightWardsBoughtInGame": 0,
                "spell1Casts": 105,
                "spell2Casts": 170,
                "spell3Casts": 26,
                "spell4Casts": 19,
                "subteamPlacement": 0,
                "summoner1Casts": 6,
                "summoner1Id": 4,
                "summoner2Casts": 8,
                "summoner2Id": 6,
                "summonerId": "c1aYZnvYsBf_kkpkYWYXn6ta5XiEVTGh7Wz2fo0SxRT0Z2Dl",
                "summonerLevel": 321,
                "summonerName": "",
                "teamEarlySurrendered": False,
                "teamId": 100,
                "teamPosition": "TOP",
                "timeCCingOthers": 31,
                "timePlayed": 2836,
                "totalAllyJungleMinionsKilled": 0,
                "totalDamageDealt": 280112,
                "totalDamageDealtToChampions": 35410,
                "totalDamageShieldedOnTeammates": 0,
                "totalDamageTaken": 56273,
                "totalEnemyJungleMinionsKilled": 0,
                "totalHeal": 9533,
                "totalHealsOnTeammates": 0,
                "totalMinionsKilled": 301,
                "totalTimeCCDealt": 176,
                "totalTimeSpentDead": 461,
                "totalUnitsHealed": 1,
                "tripleKills": 0,
                "trueDamageDealt": 13226,
                "trueDamageDealtToChampions": 11049,
                "trueDamageTaken": 3213,
                "turretKills": 5,
                "turretTakedowns": 7,
                "turretsLost": 7,
                "unrealKills": 0,
                "visionClearedPings": 0,
                "visionScore": 32,
                "visionWardsBoughtInGame": 1,
                "wardsKilled": 2,
                "wardsPlaced": 20,
                "win": False,
            },  # ...
        ],
        "platformId": "EUW1",
        "queueId": 420,
        "teams": [
            {
                "bans": [
                    {"championId": 800, "pickTurn": 1},
                    {"championId": 92, "pickTurn": 2},
                    {"championId": 51, "pickTurn": 3},
                    {"championId": 893, "pickTurn": 4},
                    {"championId": 134, "pickTurn": 5},
                ],
                "feats": {
                    "EPIC_MONSTER_KILL": {"featState": 1001},
                    "FIRST_BLOOD": {"featState": 1001},
                    "FIRST_TURRET": {"featState": 1},
                },
                "objectives": {
                    "atakhan": {"first": True, "kills": 1},
                    "baron": {"first": True, "kills": 3},
                    "champion": {"first": True, "kills": 45},
                    "dragon": {"first": True, "kills": 6},
                    "horde": {"first": False, "kills": 0},
                    "inhibitor": {"first": True, "kills": 7},
                    "riftHerald": {"first": False, "kills": 0},
                    "tower": {"first": True, "kills": 13},
                },
                "teamId": 100,
                "win": False,
            },
            {
                "bans": [
                    {"championId": 111, "pickTurn": 6},
                    {"championId": 800, "pickTurn": 7},
                    {"championId": 166, "pickTurn": 8},
                    {"championId": 234, "pickTurn": 9},
                    {"championId": 86, "pickTurn": 10},
                ],
                "feats": {
                    "EPIC_MONSTER_KILL": {"featState": 3},
                    "FIRST_BLOOD": {"featState": 3},
                    "FIRST_TURRET": {"featState": 1001},
                },
                "objectives": {
                    "atakhan": {"first": False, "kills": 0},
                    "baron": {"first": False, "kills": 0},
                    "champion": {"first": False, "kills": 49},
                    "dragon": {"first": False, "kills": 1},
                    "horde": {"first": True, "kills": 6},
                    "inhibitor": {"first": False, "kills": 1},
                    "riftHerald": {"first": True, "kills": 1},
                    "tower": {"first": False, "kills": 7},
                },
                "teamId": 200,
                "win": True,
            },
        ],
        "tournamentCode": "",
    },
}


def gameHistory(
    isWin: bool,
    duration: int,
    timestamp: int,
    queueId: int,
    championName: str,
    level: int,
    kills: int,
    deaths: int,
    assists: int,
    item0: int,
    item1: int,
    item2: int,
    item3: int,
    item4: int,
    item5: int,
    item6: int,
):
    minutes, seconds = convert_duration_to_min_sec(duration=duration)
    occurence = convert_timestamp_to_occurence_str(timestamp=timestamp)
    gamemode = convert_queueid_to_gamemode(queueId=queueId)

    return html.Div(
        className=f"p-4 border rounded-lg shadow-md {'bg-[var(--win-bg-color)]' if isWin else 'bg-[var(--lose-bg-color)]'} w-full mx-auto md:col-span-2",
        children=[
            html.Div(
                className="flex items-center justify-between",
                children=[
                    html.Div(
                        className="text-[var(--on-history)] min-w-[130px]",
                        children=[
                            html.Div(
                                className=f"{'text-[var(--win-text-color)]' if isWin else 'text-[var(--lose-text-color)]'}",
                                children=gamemode,
                            ),
                            html.Div(children=occurence),
                            html.Hr(
                                className="h-px w-12 my-2 bg-[var(--on-history)] border-0 dark:bg-[var(--on-history)]"
                            ),
                            html.Div(
                                children=f"{'Victory' if isWin else "Lose"}",
                            ),
                            html.Div(
                                children=f"{minutes} min {seconds} s",
                            ),
                        ],
                    ),
                    html.Div(
                        className="flex flex-col gap-y-2",
                        children=[
                            html.Div(
                                className="flex",
                                children=[
                                    html.Div(
                                        className="relative inline-block",
                                        children=[
                                            html.Img(
                                                className="w-16 h-16 rounded-full mx-4",
                                                alt="avatar du champion",
                                                src=f"/assets/images/champions/{championName}.jpg",
                                            ),
                                            html.Span(
                                                className="absolute bottom-0 right-3 bg-black text-white text-xs rounded-full px-1 py-0.5",
                                                children=f"{level}",
                                            ),
                                        ],
                                    ),
                                    html.Div(
                                        className="text-[var(--on-history)]",
                                        children=[
                                            html.Div(
                                                className="flex gap-x-2 font-semibold text-black",
                                                children=[
                                                    html.Div(f"{kills}"),
                                                    html.Div("/"),
                                                    html.Div(
                                                        className="text-[var(--lose-text-color)]",
                                                        children=f"{deaths}",
                                                    ),
                                                    html.Div("/"),
                                                    html.Div(f"{assists}"),
                                                ],
                                            ),
                                            html.P(
                                                children=f"{round((kills+assists)/deaths,2)} KDA"
                                            ),
                                        ],
                                    ),
                                ],
                            ),
                            html.Div(
                                className="flex gap-1",
                                children=itemHistory(
                                    itemList=[
                                        item0,
                                        item1,
                                        item2,
                                        item3,
                                        item4,
                                        item5,
                                        item6,
                                    ],
                                    isWin=isWin,
                                ),
                            ),
                        ],
                    ),
                    html.Div(
                        className="flex-grow text-center",
                        children=[
                            html.Div(
                                className="font-bold",
                                children=f"{kills} / {deaths} / {assists}",
                            ),
                        ],
                    ),
                ],
            )
        ],
    )
